### ISSUE TITLE
Magic Code verification does not work (Drupal 10.1)

### ISSUE THREAD

**Issue by chfoidl** [wunderwerkio/drupal-magic-code#2]
Using this module in Drupal 10.1 results in the following error message when verifying valid a magic code:

```
Warning: Undefined array key 0 in Drupal\Core\Database\Query\Condition->condition() (Zeile 114 in /var/www/html/web/core/lib/Drupal/Core/Database/Query/Condition.php)
#0 /var/www/html/web/core/includes/bootstrap.inc(164): _drupal_error_handler_real(2, 'Undefined array...', '/var/www/html/w...', 114)
#1 /var/www/html/web/core/lib/Drupal/Core/Database/Query/Condition.php(114): _drupal_error_handler(2, 'Undefined array...', '/var/www/html/w...', 114)
#2 /var/www/html/web/core/lib/Drupal/Core/Database/Query/QueryConditionTrait.php(27): Drupal\Core\Database\Query\Condition->condition('magic_code.clie...', Array, '=')
#3 /var/www/html/web/core/lib/Drupal/Core/Entity/Query/Sql/Condition.php(77): Drupal\Core\Database\Query\Select->condition('magic_code.clie...', Array, NULL)
#4 /var/www/html/web/core/lib/Drupal/Core/Entity/Query/Sql/Query.php(176): Drupal\Core\Entity\Query\Sql\Condition->compile(Object(Drupal\mysql\Driver\Database\mysql\Select))
#5 /var/www/html/web/core/lib/Drupal/Core/Entity/Query/Sql/Query.php(341): Drupal\Core\Entity\Query\Sql\Query->compile()
#6 /var/www/html/web/modules/contrib/magic_code/src/MagicCodeManager.php(143): Drupal\Core\Entity\Query\Sql\Query->__toString()
#7 /var/www/html/web/modules/contrib/magic_code/src/Plugin/VerificationProvider/MagicCode.php(105): Drupal\magic_code\MagicCodeManager->verify('6DC-RZT', 'login', 1, Object(Drupal\user\Entity\User), Object(Drupal\consumers\Entity\Consumer), 'christian@wunde...')
#8 /var/www/html/web/modules/contrib/magic_code/src/Plugin/VerificationProvider/MagicCode.php(159): Drupal\magic_code\Plugin\VerificationProvider\MagicCode->Drupal\magic_code\Plugin\VerificationProvider\{closure}(Object(Drupal\consumers\Entity\Consumer), '6DC-RZT')
#9 /var/www/html/web/modules/contrib/magic_code/src/Plugin/VerificationProvider/MagicCode.php(120): Drupal\magic_code\Plugin\VerificationProvider\MagicCode->Drupal\magic_code\Plugin\VerificationProvider\{closure}(Object(Closure))
#10 /var/www/html/web/modules/contrib/verification/src/Service/RequestVerifier.php(49): Drupal\magic_code\Plugin\VerificationProvider\MagicCode->verifyLogin(Object(Symfony\Component\HttpFoundation\Request), 'login', Object(Drupal\user\Entity\User), 'christian@wunde...')
#11 /var/www/html/web/modules/contrib/simple_oauth_auth_code/src/Plugin/rest/resource/AuthCodeResource.php(169): Drupal\verification\Service\RequestVerifier->verifyLogin(Object(Symfony\Component\HttpFoundation\Request), 'login', Object(Drupal\user\Entity\User), 'christian@wunde...')
#12 [internal function]: Drupal\simple_oauth_auth_code\Plugin\rest\resource\AuthCodeResource->post(Object(Symfony\Component\HttpFoundation\Request))
#13 /var/www/html/web/core/modules/rest/src/RequestHandler.php(219): call_user_func_array(Array, Array)
#14 /var/www/html/web/core/modules/rest/src/RequestHandler.php(68): Drupal\rest\RequestHandler->delegateToRestResourcePlugin(Object(Drupal\Core\Routing\RouteMatch), Object(Symfony\Component\HttpFoundation\Request), Array, Object(Drupal\simple_oauth_auth_code\Plugin\rest\resource\AuthCodeResource))
#15 [internal function]: Drupal\rest\RequestHandler->handle(Object(Drupal\Core\Routing\RouteMatch), Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\rest\Entity\RestResourceConfig))
#16 /var/www/html/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array)
#17 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(583): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#18 /var/www/html/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#19 /var/www/html/web/modules/custom/ww_jsonapi/src/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(32): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)
#20 /var/www/html/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\ww_jsonapi\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)
#21 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(166): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#22 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#23 /var/www/html/web/modules/contrib/simple_oauth/src/HttpMiddleware/BasicAuthSwap.php(54): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#24 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/Session.php(58): Drupal\simple_oauth\HttpMiddleware\BasicAuthSwap->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#25 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#26 /var/www/html/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#27 /var/www/html/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#28 /var/www/html/vendor/asm89/stack-cors/src/Cors.php(53): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#29 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Asm89\Stack\Cors->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#30 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#31 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/StackedHttpKernel.php(51): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#32 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(704): Drupal\Core\StackMiddleware\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#33 /var/www/html/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#34 {main}

```

**Comment by chfoidl** [comment]
Fixed by #3
